name: pre-merge
on: workflow_dispatch  # manually trigger

jobs:
  build:
    runs-on: ubuntu-20.04  # TODO: redirect to a pyenv / poetry image
    strategy:
      matrix:
        python-minor-version: ["8", "10"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.${{ matrix.python-minor-version }}"
    - name: Python Version
      run: python3 --version
    - name: Dependencies
      run: echo "Installing dependencies"
    - name: Formatting
      run: echo "Formatting"
    - name: Linting
      run: echo "Linting"
    - name: Tests
      run: echo "Tests"
